### ISSUE TITLE
rip cpu with that

### ISSUE THREAD

**Issue by ghost** [Muqsit/VanillaGenerator#1]
i have a bigger suggestion if you want a good generation. Actually DaPorkchop from Nukkit already do a good job by creating new noise what is faster then Glowstone one, you can check:

https://github.com/PorkStudios/PorkLib

**Comment by Muqsit** [comment]
Yup, the generator isn't that fast. I'm considering implementing everything before doing any optimizations whatsoever.

**Comment by NycuRO** [comment]
![image](https://user-images.githubusercontent.com/13573011/60976440-5f10aa80-a336-11e9-933d-9f8ef813dfe2.png)

You kinda  need to remove populators from pmmp

**Comment by Muqsit** [comment]
Oh those aren't pocketmine's populators, they are GlowstoneMC's Lake object. I most likely didn't port it correctly.

**Comment by Muqsit** [comment]
The floating lake issue has been fixed in https://github.com/Muqsit/VanillaGenerator-master/commit/e819287dc8ec5d8f7a2fe07d9f0d34865a52af32

**Comment by NycuRO** [comment]
@Muqsit What about using taylor series instead of trigonometric and exponential functions? I think will be faster.

**Comment by NycuRO** [comment]
@Muqsit abandonated?

**Comment by NycuRO** [comment]
any news?

**Comment by ZloyNick** [comment]
> any news?

I think, that this generation couldn't be updated.

**Comment by Muqsit** [comment]
There are not many avenues for optimization in this plugin. The performance is much better since PHP 8.1 (and JIT). If you are looking for a more performant alternative, NetherGames maintains a version of this repository rewritten in C++ that may be of your interest: https://github.com/NetherGamesMC/ext-vanillagenerator.
