### ISSUE TITLE
Bug or not? 

### ISSUE THREAD

**Issue by ipad54** [Muqsit/VanillaGenerator#17]
![Screenshot_20210123_121721_com mojang minecraftpe](https://user-images.githubusercontent.com/63200545/105574374-2ea42c00-5d75-11eb-9dc6-b9a9edc83d03.jpg)
![Screenshot_20210123_121712_com mojang minecraftpe](https://user-images.githubusercontent.com/63200545/105574376-306def80-5d75-11eb-983c-700ea112f2f6.jpg)

**Comment by Muqsit** [comment]
This is a port of GlowstoneMC's biome generation, please check their source code while comparison.

**Comment by thebigsmileXD** [comment]
Might be caused by coarse dirt being classified as dirt in MCPE whereas in Java it has its own tags
