### ISSUE TITLE
Question und Suggestion 

### ISSUE THREAD

**Issue by TheBalkanDev** [Muqsit/VanillaGenerator#23]
Sry for opening the second Issue this day but the other one was closed. 

I have 3 Main Questions.

 1. Do you have Discord?
 2. Has this Generator Caves?
 3. I know this is an 1:1 Port, but you can add an 1.16 like Nether?

**Comment by TheBalkanDev** [comment]
The Question with the Caves was dumm.
I looked in Code and I answered myself.

**Comment by Muqsit** [comment]
I neither have the expertise nor the time to figure out how noise generation works and utilize it for terrain generation, which is why this project is solely a direct-port of GlowstoneMC's world generator.
Feel free to fork / copy / modify the project.

**Comment by thebigsmileXD** [comment]
Maybe you should rename the repo to GlowstoneGenerator
