### ISSUE TITLE
Test for Pocketmine 4.0.0 Beta 1

### ISSUE THREAD

**Issue by MonoAdrian23** [Muqsit/VanillaGenerator#26]
I have tried this Plugin and have Set vanilla_overworld
At next i have delete the old world and restart the Server.
But the world is the Same and No Vanilla World is created.
The Plugin is activ.

**Comment by Muqsit** [comment]
Delete the world _after_ stopping the server.
Edit your pocketmine.yml file as stated in README.md, then delete your `worlds/world/` and `worlds/nether/` folders and start the server.
Be sure to follow the steps thoroughly.
