### ISSUE TITLE
Time changes vision in the nether

### ISSUE THREAD

**Issue by MrBlasyMSK** [Muqsit/VanillaGenerator#32]
Watch the video and you will understand better. It would be great if there was an option to always stay on the same schedule or disable it so it wouldn't affect.
https://streamable.com/a5ih12

**Comment by Muqsit** [comment]
That's beyond what this plugin is meant for. This is just a port of glowstonemc's world terrain generator. You'd have to wait until PocketMine supports nether dimensions.
