### ISSUE TITLE
Ores

### ISSUE THREAD

**Issue by SiahRBLX** [Muqsit/VanillaGenerator#35]
No Vanilla ores spawn in world

**Comment by MonoAdrian23** [comment]
What do you mean with "Vanilla" Ores?
I use it and i found Diamonds, Iron, gold etc

**Comment by SiahRBLX** [comment]
> What do you mean with "Vanilla" Ores?
> I use it and i found Diamonds, Iron, gold etc

How often?

**Comment by MonoAdrian23** [comment]
Its normal generated.
Works perfect.

**Comment by Muqsit** [comment]
Ore generation appears to be functioning correctly. Tested with the following `pocketmine.yml` configuration:
```yaml
worlds:
 world_test:
  generator: vanilla_overworld
  seed: 404
```
![image](https://user-images.githubusercontent.com/15074389/209903719-d18bd2ee-7fe6-417f-8afb-1ab499bc75e1.png)
