### ISSUE TITLE
MegaPineTree TypeError

### ISSUE THREAD

**Issue by NickteeChunky** [Muqsit/VanillaGenerator#40]
I was running this through MultiWorld and encountered this

TypeError: "czechpmdevs\multiworld\libs\muqsit\vanillagenerator\generator\object\tree\MegaPineTree::generatePodzolPatch(): Argument #3 ($source_z) must be of type int, float given, called in C:\Users\NickteeChunky\Desktop\Factions\plugins\MultiWorld_v2.0.0-beta1\src\czechpmdevs\multiworld\libs\muqsit\vanillagenerator\generator\object\tree\MegaPineTree.php on line 44" (EXCEPTION) in "C:/Users/NickteeChunky/Desktop/Factions/plugins/MultiWorld_v2.0.0-beta1/src/czechpmdevs/multiworld/libs/muqsit/vanillagenerator/generator/object/tree/MegaPineTree" at line 49

Just by the looks of things, I think the line's meant to be `$this->generatePodzolPatch($source_x - 3 + $n % 8, $source_y, $source_z - 3 + $n % 8, $world);`

**Comment by Muqsit** [comment]
The difference in the way the x and z coordinates are being calculated [there](https://github.com/Muqsit/VanillaGenerator/blob/34fc72fa3088736d7f507eeabe3d490032cceff6/src/muqsit/vanillagenerator/generator/object/tree/MegaPineTree.php#L44) is strange, although it appears that the same operation is being performed in Minecraft's source code as well: https://github.com/wout-junius/Minecraft_Mod_Testing/blob/14cb556b0edb4b67db606ea8ae35bde692a320db/build/tmp/expandedArchives/forge-1.14.4-28.1.0_mapped_snapshot_20191205-1.14.3-sources.jar_53d2a6cb7bb047a7513dac2d866d58cd/net/minecraft/world/gen/feature/MegaPineTree.java#L80.

However the equivalent for `int / int` done in Java would be `intdiv(int, int)` in PHP.
From https://minecraft.fandom.com/wiki/Spruce, there is some special behaviour podzol generation exhibits during generation. I believe the difference in calculating x and z values accommodates for that:
![image](https://user-images.githubusercontent.com/15074389/209897040-42eb5fff-a162-4901-bcdb-b2b53fca6969.png)

**Comment by Muqsit** [comment]
Resolved in 89e027abf4acb38cab40727feb300e15eff2f2b8 (pm4), dde05edaa0d355bb6bbc8308d37e835579cc10fd (pm5)
